In [19]:
import numpy as np

In [39]:
rng = np.random.default_rng(seed=12345)

In [21]:
np.ones((10, 5)).shape

(10, 5)

In [22]:
np.ones((3,4,5), dtype=np.float64).strides

(160, 40, 8)

In [23]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)

True

In [24]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [27]:
arr.reshape((1,8))
arr.reshape((8,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [28]:
arr.reshape((-1,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [29]:
arr = np.arange(15).reshape((5,3))

In [30]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [31]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [35]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [40]:
arr = rng.standard_normal((5,2))

In [42]:
arr

array([[-1.42382504,  1.26372846],
       [-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465],
       [-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

In [43]:
first, second, third = np.split(arr, [1,3])

In [44]:
first

array([[-1.42382504,  1.26372846]])

In [45]:
second

array([[-0.87066174, -0.25917323],
       [-0.07534331, -0.74088465]])

In [46]:
third

array([[-1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306]])

In [48]:
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = rng.standard_normal((3,2))
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 0.78884434, -1.25666813],
       [ 0.57585751,  1.39897899],
       [ 1.32229806, -0.29969852]])

In [49]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 0.78884434, -1.25666813,  3.        ],
       [ 0.57585751,  1.39897899,  4.        ],
       [ 1.32229806, -0.29969852,  5.        ]])

# Repeating elements

In [50]:
arr = np.arange(3)
arr

array([0, 1, 2])

In [51]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [53]:
arr.repeat([2,3,4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [54]:
arr = rng.standard_normal((2,2))

In [55]:
arr

array([[ 0.90291934, -1.62158273],
       [-0.15818926,  0.44948393]])

In [56]:
arr.repeat(2, axis=0)

array([[ 0.90291934, -1.62158273],
       [ 0.90291934, -1.62158273],
       [-0.15818926,  0.44948393],
       [-0.15818926,  0.44948393]])

In [57]:
arr 

array([[ 0.90291934, -1.62158273],
       [-0.15818926,  0.44948393]])

In [58]:
np.tile(arr,2)

array([[ 0.90291934, -1.62158273,  0.90291934, -1.62158273],
       [-0.15818926,  0.44948393, -0.15818926,  0.44948393]])

# A.3 Broadcasting

In [59]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [61]:
arr * 4

array([ 0,  4,  8, 12, 16])

In [62]:
arr = rng.standard_normal((4,3))

In [63]:
arr.mean(0)

array([0.21427922, 0.05955622, 0.1205802 ])

In [64]:
demeaned = arr-arr.mean(0)

In [65]:
demeaned

array([[-1.55788029, -0.14124381,  1.60415973],
       [ 2.40388021,  0.71780513,  0.708053  ],
       [-1.17326753, -1.2689445 , -1.53287221],
       [ 0.32726761,  0.69238318, -0.77934052]])

In [66]:
arr = np.arange(10)
np.add.reduce(arr)

np.int64(45)