In [15]:
import pandas as pd
import numpy as np
import patsy

In [2]:
data = pd.DataFrame({
    'x0':[1,2,3,4,5],
    'x1':[0.01,-0.01,0.25,-4.1,0.],
    'y': [-1.5,0.,3.6,1.3,-2.]})

In [3]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [9]:
col_names = list(data.columns)
col_names

['x0', 'x1', 'y']

In [5]:
data.to_numpy()

array([[ 1.  ,  0.01, -1.5 ],
       [ 2.  , -0.01,  0.  ],
       [ 3.  ,  0.25,  3.6 ],
       [ 4.  , -4.1 ,  1.3 ],
       [ 5.  ,  0.  , -2.  ]])

In [10]:
pd.DataFrame(data.to_numpy(), columns=col_names)

x0    x1    y
0  1.0  0.01 -1.5
1  2.0 -0.01  0.0
2  3.0  0.25  3.6
3  4.0 -4.10  1.3
4  5.0  0.00 -2.0

In [11]:
choosen_cols = ["x0", 'x1']
data.loc[:,choosen_cols].to_numpy()

array([[ 1.  ,  0.01],
       [ 2.  , -0.01],
       [ 3.  ,  0.25],
       [ 4.  , -4.1 ],
       [ 5.  ,  0.  ]])

In [12]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
 categories=['a', 'b'])
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [14]:
dummies = pd.get_dummies(data.category, prefix="category")
dummies

category_a  category_b
0        True       False
1       False        True
2        True       False
3        True       False
4       False        True

In [16]:
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

In [20]:
data = data.drop(columns=["category"])

In [21]:
data

x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

In [22]:
y, X = patsy.dmatrices('y ~ x0 + x1', data)

In [23]:
y

DesignMatrix with shape (5, 1)
     y
  -1.5
   0.0
   3.6
   1.3
  -2.0
  Terms:
    'y' (column 0)

In [24]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [25]:
patsy.dmatrices('y ~ x0 + x1', data)[1]

DesignMatrix with shape (5, 3)
  Intercept  x0     x1
          1   1   0.01
          1   2  -0.01
          1   3   0.25
          1   4  -4.10
          1   5   0.00
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'x1' (column 2)

In [26]:
coef, resid, _, _ = np.linalg.lstsq(X, y)

In [27]:
coef

array([[ 0.31290976],
       [-0.07910564],
       [-0.26546384]])

In [30]:
coef = pd.Series(coef.squeeze(), index=X.design_info.column_names)
coef

Intercept    0.312910
x0          -0.079106
x1          -0.265464
dtype: float64

In [31]:
y, X = patsy.dmatrices('y ~ x0 + np.log(np.abs(x1) + 1)', data)

In [32]:
X

DesignMatrix with shape (5, 3)
  Intercept  x0  np.log(np.abs(x1) + 1)
          1   1                 0.00995
          1   2                 0.00995
          1   3                 0.22314
          1   4                 1.62924
          1   5                 0.00000
  Terms:
    'Intercept' (column 0)
    'x0' (column 1)
    'np.log(np.abs(x1) + 1)' (column 2)

In [33]:
new_data = pd.DataFrame({
 'x0': [6, 7, 8, 9],
 'x1': [3.1, -0.5, 0, 2.3],
 'y': [1, 2, 3, 4]})
new_X = patsy.build_design_matrices([X.design_info], new_data)

In [34]:
new_X

[DesignMatrix with shape (4, 3)
   Intercept  x0  np.log(np.abs(x1) + 1)
           1   6                 1.41099
           1   7                 0.40547
           1   8                 0.00000
           1   9                 1.19392
   Terms:
     'Intercept' (column 0)
     'x0' (column 1)
     'np.log(np.abs(x1) + 1)' (column 2)]

In [35]:
data = pd.DataFrame({
 'key1': ['a', 'a', 'b', 'b', 'a', 'b', 'a', 'b'],
 'key2': [0, 1, 0, 1, 0, 1, 0, 0],
 'v1': [1, 2, 3, 4, 5, 6, 7, 8],
 'v2': [-1, 0, 2.5, -0.5, 4.0, -1.2, 0.2, -1.7]
})
y, X = patsy.dmatrices('v2 ~ key1', data)
X

DesignMatrix with shape (8, 2)
  Intercept  key1[T.b]
          1          0
          1          0
          1          1
          1          1
          1          0
          1          1
          1          0
          1          1
  Terms:
    'Intercept' (column 0)
    'key1' (column 1)

In [36]:
import statsmodels.api as sm
import statsmodels.formula.api as smf 

In [37]:
rng = np.random.default_rng(seed=0)

In [38]:
def dnorm(mean, variance, size =1):
    if isinstance(size, int):
        size =size,
    return mean + np.sqrt(variance) * rng.standard_normal(*size)

In [39]:
N = 100
X = np.c_[dnorm(0,0.4,size=N),
    dnorm(0, 0.6, size=N),
    dnorm(0, 0.2, size=N)]
eps = dnorm(0, 0.1, size=N)
beta = [0.1, 0.3, 0.5]
y = np.dot(X, beta) + eps

In [40]:
X[:5]

array([[ 0.07951877,  0.38937646, -0.29674196],
       [-0.08355045,  0.76662842, -0.2743288 ],
       [ 0.40503885, -0.12726204, -0.71784463],
       [ 0.06634466, -0.83219944,  0.32617497],
       [-0.33878706,  0.67625554,  0.36051648]])

In [41]:
y[:5]

array([ 0.35689773,  0.28592933, -0.18003445, -1.27283603,  0.43167456])

In [42]:
X_model = sm.add_constant(X)

In [43]:
model = sm.OLS(y, X)

In [44]:
results = model.fit()

In [45]:
print(results.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.565
Model:                            OLS   Adj. R-squared (uncentered):              0.552
Method:                 Least Squares   F-statistic:                              42.00
Date:                Wed, 25 Feb 2026   Prob (F-statistic):                    1.75e-17
Time:                        16:27:32   Log-Likelihood:                         -17.975
No. Observations:                 100   AIC:                                      41.95
Df Residuals:                      97   BIC:                                      49.77
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [46]:
data = pd.DataFrame(X, columns=['col0', 'col1', 'col2'])

In [47]:
results = smf.ols('y~col0+col1+col2', data=data).fit()

In [48]:
results.params

Intercept   -0.011922
col0         0.073638
col1         0.253144
col2         0.514649
dtype: float64

In [50]:
init_x = 4
values = [init_x, init_x]
N = 1000
b0 = 0.8
b1 = -0.4
noise = dnorm(0, 0.1, N)
for i in range(N):
    new_x = values[-1] * b0 + values[-2] * b1 + noise[i]
    values.append(new_x)

In [51]:
from statsmodels.tsa.ar_model import AutoReg

In [52]:
MAXLAGS = 5
model = AutoReg(values, MAXLAGS)
results = model.fit()

In [53]:
results.params

array([-0.00278979,  0.80909884, -0.40742618,  0.08236254, -0.05740198,
        0.00699929])

In [54]:
train = pd.read_csv('datasets/titanic/train.csv')
test = pd.read_csv('datasets/titanic/test.csv')
train.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [55]:
train.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [57]:
impute_value = train['Age'].median()
train['Age'] = train['Age'].fillna(impute_value)
test['Age'] = test['Age'].fillna(impute_value)

In [58]:
train['IsFemale'] = (train['Sex'] == 'female').astype(int)
test['IsFemale'] = (test['Sex'] == 'female').astype(int)

In [59]:
predictors = ['Pclass', 'IsFemale', 'Age']

In [60]:
X_train = train[predictors].to_numpy()
X_test = test[predictors].to_numpy()
y_train = train["Survived"].to_numpy()

In [61]:
from sklearn.linear_model import LogisticRegression

In [62]:
y_train[:5]

array([0, 1, 1, 1, 0])

In [64]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_predict = model.predict(X_test)

In [66]:
from sklearn.linear_model import LogisticRegressionCV
model_cv = LogisticRegressionCV(Cs=10)
model_cv.fit(X_train, y_train)
from sklearn.model_selection import cross_val_score
model = LogisticRegression(C=10)
scores = cross_val_score(model, X_train, y_train, cv=4)
scores

/home/lenny/projects/programming-books/data-analysis-in-python/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
/home/lenny/projects/programming-books/data-analysis-in-python/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of L

array([0.77578475, 0.79820628, 0.77578475, 0.78828829])